'use client';

import PageHeader from '@/components/shared/PageHeader';
import { useDarkMode } from '@/components/Providers';
import { palette } from '@leafygreen-ui/palette';

const DATA_GENERATORS = [
  {
    category: 'SCADA & Meters',
    color: '#016BF8',
    description: 'Supervisory Control and Data Acquisition systems and smart meters deployed across physical energy assets.',
    sources: [
      { name: 'Meter Reading Events', detail: 'Real-time energy output readings from smart meters installed at each generation asset (wind turbines, solar panels, hydro plants, etc.).' },
      { name: 'Performance Variance', detail: 'Delta between forecasted and actual generation output, used to detect underperformance and trigger maintenance alerts.' },
      { name: 'Solar Irradiance Forecast', detail: 'Predicted solar radiation levels from weather sensors co-located at solar farm sites, feeding into output forecasting models.' },
    ],
  },
  {
    category: 'Other Systems',
    color: '#00ED64',
    description: 'External market and meteorological systems providing contextual data for trading and forecasting.',
    sources: [
      { name: 'WindForecast', detail: 'Wind speed and direction forecasts from meteorological APIs (e.g. ECMWF), used to predict wind farm output for Day-Ahead market bidding.' },
      { name: 'Solar Irradiance Forecast', detail: 'Regional solar irradiance predictions aggregated from national weather services, covering the Iberian Peninsula and Central Europe.' },
      { name: 'Price Events (ENTSO-E, EPEX Spot, EEX)', detail: 'Wholesale electricity prices from European power exchanges: ENTSO-E Transparency Platform (Day-Ahead), EPEX SPOT (Intraday), and EEX (Futures & Flexibility).' },
    ],
  },
  {
    category: 'App',
    color: '#FFC010',
    description: 'Application-layer events generated by trader actions and automated portfolio management workflows.',
    sources: [
      { name: 'Trade Executed', detail: 'Events emitted when a trader submits a buy/sell order via the Trading Dashboard, recording volume, price, market channel, and asset ID.' },
      { name: 'Capacity Allocation', detail: 'Commands that assign committed generation capacity to specific market channels (Day-Ahead, Intraday, Flexibility), updating the position gap in real time.' },
    ],
  },
];

export default function ArchitecturePage() {
  const { darkMode } = useDarkMode();
  const textColor = darkMode ? palette.gray.light1 : palette.gray.dark2;
  const borderColor = darkMode ? palette.gray.dark2 : palette.gray.light2;
  const cardBg = darkMode ? '#0a1622' : palette.white;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
      <PageHeader
        title="Architecture"
        subtitle="System architecture diagram"
      />

      {/* Architecture diagram — rendered at native 960×540, centered, no upscaling */}
      <div style={{ display: 'flex', justifyContent: 'center', overflowX: 'auto' }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/img/architecture.jpeg"
          alt="System Architecture Diagram"
          width={960}
          height={540}
          style={{ borderRadius: '12px', display: 'block' }}
        />
      </div>

      {/* Data Generator references */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        <div style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '1.5px', textTransform: 'uppercase', color: palette.green.base, marginBottom: '4px' }}>
          Data Generator Reference
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '16px' }}>
          {DATA_GENERATORS.map((group) => (
            <div key={group.category} style={{
              background: cardBg,
              border: `1.5px solid ${borderColor}`,
              borderTop: `3px solid ${group.color}`,
              borderRadius: '10px',
              padding: '16px',
            }}>
              <div style={{ fontSize: '13px', fontWeight: 700, color: group.color, marginBottom: '4px' }}>
                {group.category}
              </div>
              <div style={{ fontSize: '11px', color: textColor, marginBottom: '12px', lineHeight: 1.5 }}>
                {group.description}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {group.sources.map((source) => (
                  <div key={source.name}>
                    <div style={{ fontSize: '11px', fontWeight: 700, color: group.color, marginBottom: '2px' }}>
                      {source.name}
                    </div>
                    <div style={{ fontSize: '11px', color: textColor, lineHeight: 1.6 }}>
                      {source.detail}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
