import type { ComplianceScenario } from './types';

export const COMPLIANCE_SCENARIOS: ComplianceScenario[] = [
  {
    id: 'imbalance-settlement',
    title: 'Imbalance Settlement Audit',
    regulation: 'Electricity Balancing (EU) 2017/2195',
    description:
      'TSO/BRP dispute over a 15-min ISP shortfall. Replay corrected meter data to prove the BRP was actually +0.9 MWh long, not -12 MW short.',
    events: [
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 1,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T13:45:00Z',
        payload: {
          trade_id: 'TRD-2024-78431',
          portfolio_id: 'brp-de-001',
          instrument_id: 'EPEX-DE-INTRA-QH',
          price: 82.5,
          quantity: 50,
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20241215-1400' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 2,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T13:50:00Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-QH', price: 84.0 },
        metadata: { schemaVersion: 1 },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 3,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T14:00:00Z',
        payload: { meter_id: 'de-sub-4471', reading: 1204.8 },
        metadata: { schemaVersion: 1, reading_type: 'isp_start', source: 'MDL-50Hertz' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 4,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T14:05:00Z',
        payload: {
          trade_id: 'TRD-2024-78432',
          portfolio_id: 'brp-de-001',
          instrument_id: 'EPEX-DE-INTRA-QH',
          price: 86.2,
          quantity: -20,
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20241215-1400' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 5,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T14:15:00Z',
        payload: { meter_id: 'de-sub-4471', reading: 1243.0 },
        metadata: { schemaVersion: 1, reading_type: 'isp_end', source: 'MDL-50Hertz' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 6,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T14:16:00Z',
        payload: { instrument_id: 'EPEX-DE-IMBAL-QH', price: 850.0 },
        metadata: { schemaVersion: 1, price_type: 'imbalance_price', source: '50Hertz-settlement' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 7,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-16T09:30:00Z',
        payload: { meter_id: 'de-sub-4471', reading: 1241.9 },
        metadata: {
          schemaVersion: 1,
          reading_type: 'isp_end',
          corrects_version: 5,
          correction_reason: 'meter_calibration_adjustment',
          source: 'MDL-50Hertz-correction',
        },
      },
    ],
  },
  {
    id: 'remit-surveillance',
    title: 'REMIT Trade Surveillance',
    regulation: 'REMIT (EU) 1227/2011',
    description:
      'ACER spoofing investigation — immutable trail of rapid orders, cancellations, and price impact on EPEX-DE-INTRA-1700.',
    events: [
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 1,
        eventType: 'InstrumentListed',
        timestamp: '2024-12-15T06:00:00Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', name: 'EPEX DE Intraday 17:00 Delivery' },
        metadata: { schemaVersion: 1, market: 'EPEX_SPOT', delivery_zone: 'DE-LU' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 2,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:48:12Z',
        payload: {
          trade_id: 'ORD-2024-AW-5501',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 72.0,
          quantity: 10,
        },
        metadata: { schemaVersion: 1, trader_id: 'AW-TR-042', order_type: 'limit_buy' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 3,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T16:48:13Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', price: 78.5 },
        metadata: { schemaVersion: 1, trigger: 'order_book_update' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 4,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:49:04Z',
        payload: {
          trade_id: 'ORD-2024-AW-5514',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 95.0,
          quantity: 10,
        },
        metadata: { schemaVersion: 1, trader_id: 'AW-TR-042', order_type: 'limit_buy' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 5,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T16:49:05Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', price: 118.0 },
        metadata: { schemaVersion: 1, trigger: 'order_book_update' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 6,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:49:45Z',
        payload: {
          trade_id: 'ORD-2024-AW-5520',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 116.5,
          quantity: -120,
        },
        metadata: { schemaVersion: 1, trader_id: 'AW-TR-042', order_type: 'market_sell' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 7,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T16:50:02Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', price: 78.0 },
        metadata: { schemaVersion: 1, trigger: 'order_book_update' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 8,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:52:00Z',
        payload: {
          trade_id: 'COMPL-2024-FREEZE-0042',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 0.0,
          quantity: 0,
        },
        metadata: {
          schemaVersion: 1,
          trader_id: 'COMPLIANCE-SYSTEM',
          order_type: 'compliance_freeze',
          investigation_ref: 'ACER-2024-DE-SPOOF-0891',
        },
      },
    ],
  },
];
