import type { ComplianceScenario } from './types';

export const COMPLIANCE_SCENARIOS: ComplianceScenario[] = [
  {
    id: 'imbalance-settlement',
    title: 'Imbalance Settlement Audit',
    regulation: 'Electricity Balancing (EU) 2017/2195',
    description:
      'Wind forecast updated for Hollandse Kust, BRP committed based on stale forecast, actual output exceeded commitment, TSO incorrectly charged imbalance — dispute filed and corrected via immutable event trail.',
    events: [
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'WeatherForecast',
        version: 1,
        eventType: 'WindForecastUpdated',
        timestamp: '2025-03-12T06:00:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          capacityMW: 200,
          forecastWindowStart: '2025-03-12T14:00:00Z',
          forecastWindowEnd: '2025-03-12T14:15:00Z',
          forecastedOutputMW: 128,
          confidencePercent: 82,
          windSpeedMs: 9.4,
          provider: 'KNMI',
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', source: 'KNMI-offshore-model' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'TradingPosition',
        version: 2,
        eventType: 'CapacityAllocationSet',
        timestamp: '2025-03-12T08:30:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          allocatedMW: 128,
          ispStart: '2025-03-12T14:00:00Z',
          ispEnd: '2025-03-12T14:15:00Z',
          basisForecastVersion: 1,
          brpId: 'BRP-NL-LEAFY-001',
          market: 'EPEX-NL-DA',
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', trader: 'desk-nl-wind' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'TradingPosition',
        version: 3,
        eventType: 'TradeExecuted',
        timestamp: '2025-03-12T09:15:00Z',
        payload: {
          tradeId: 'TRD-2025-NL-40221',
          assetId: 'ASSET-WIND-NL-001',
          instrument: 'EPEX-NL-DA-QH-1400',
          side: 'sell',
          priceMWh: 74.20,
          quantityMW: 128,
          ispStart: '2025-03-12T14:00:00Z',
          ispEnd: '2025-03-12T14:15:00Z',
          brpId: 'BRP-NL-LEAFY-001',
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', orderType: 'day_ahead_sell' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'WeatherForecast',
        version: 4,
        eventType: 'WindForecastUpdated',
        timestamp: '2025-03-12T12:45:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          capacityMW: 200,
          forecastWindowStart: '2025-03-12T14:00:00Z',
          forecastWindowEnd: '2025-03-12T14:15:00Z',
          forecastedOutputMW: 172,
          confidencePercent: 91,
          windSpeedMs: 12.8,
          provider: 'KNMI',
          previousForecastMW: 128,
          deltaPercent: 34.4,
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', source: 'KNMI-offshore-model', supersedes_version: 1 },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'AssetTelemetry',
        version: 5,
        eventType: 'MeterReadingRecorded',
        timestamp: '2025-03-12T14:00:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          meterId: 'NL-HKW-METER-001',
          readingMWh: 8412.60,
          readingType: 'isp_start',
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', source: 'TenneT-MDL' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'AssetTelemetry',
        version: 6,
        eventType: 'MeterReadingRecorded',
        timestamp: '2025-03-12T14:15:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          meterId: 'NL-HKW-METER-001',
          readingMWh: 8455.90,
          readingType: 'isp_end',
          actualOutputMW: 173.2,
          ispDurationMinutes: 15,
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', source: 'TenneT-MDL' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'AssetTelemetry',
        version: 7,
        eventType: 'PerformanceVarianceDetected',
        timestamp: '2025-03-12T14:16:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          committedMW: 128,
          actualMW: 173.2,
          varianceMW: 45.2,
          variancePercent: 35.3,
          direction: 'over_delivery',
          ispStart: '2025-03-12T14:00:00Z',
          ispEnd: '2025-03-12T14:15:00Z',
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', trigger: 'auto_meter_comparison' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'TradingPosition',
        version: 8,
        eventType: 'PositionGapDetected',
        timestamp: '2025-03-12T14:20:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          brpId: 'BRP-NL-LEAFY-001',
          committedMW: 128,
          actualMW: 173.2,
          gapMW: 45.2,
          gapDirection: 'long',
          imbalancePriceMWh: 320.00,
          estimatedExposureEUR: 3616.00,
          ispStart: '2025-03-12T14:00:00Z',
          ispEnd: '2025-03-12T14:15:00Z',
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', source: 'TenneT-settlement-prelim' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'TradingPosition',
        version: 9,
        eventType: 'PnlSnapshotRecorded',
        timestamp: '2025-03-12T14:25:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          brpId: 'BRP-NL-LEAFY-001',
          dayAheadRevenue: 2374.40,
          imbalanceCharge: -3616.00,
          netPnl: -1241.60,
          dayAheadPriceMWh: 74.20,
          imbalancePriceMWh: 320.00,
          committedMW: 128,
          actualMW: 173.2,
          overDeliveryMW: 45.2,
          settlementStatus: 'preliminary',
          note: 'TSO applied negative imbalance charge for over-delivery — dispute pending',
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20250312-1400', source: 'internal-pnl-engine' },
      },
      {
        streamId: 'ASSET-WIND-NL-001',
        streamType: 'TradingPosition',
        version: 10,
        eventType: 'PnlSnapshotRecorded',
        timestamp: '2025-03-13T10:00:00Z',
        payload: {
          assetId: 'ASSET-WIND-NL-001',
          assetName: 'Hollandse Kust Wind',
          brpId: 'BRP-NL-LEAFY-001',
          dayAheadRevenue: 2374.40,
          imbalanceCredit: 1446.40,
          netPnl: 3820.80,
          dayAheadPriceMWh: 74.20,
          imbalancePriceMWh: 128.00,
          committedMW: 128,
          actualMW: 173.2,
          overDeliveryMW: 45.2,
          settlementStatus: 'corrected',
          correctionReason: 'Over-delivery in long system credited at single imbalance price per EBGL Art. 55',
          disputeRef: 'DISP-2025-NL-00417',
          correctsVersion: 9,
        },
        metadata: {
          schemaVersion: 1,
          correlationId: 'isp-20250312-1400',
          source: 'TenneT-settlement-final',
          corrects_version: 9,
          dispute_resolution: 'accepted',
        },
      },
    ],
  },
];
