import type { ComplianceScenario } from './types';

export const COMPLIANCE_SCENARIOS: ComplianceScenario[] = [
  {
    id: 'imbalance-settlement',
    title: 'Imbalance Settlement Audit',
    regulation: 'Electricity Balancing (EU) 2017/2195',
    description:
      'TSO/BRP dispute over a 15-min ISP shortfall. Replay corrected meter data to prove the BRP was actually +0.9 MWh long, not -12 MW short.',
    events: [
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 1,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T13:45:00Z',
        payload: {
          trade_id: 'TRD-2024-78431',
          portfolio_id: 'brp-de-001',
          instrument_id: 'EPEX-DE-INTRA-QH',
          price: 82.5,
          quantity: 50,
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20241215-1400' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 2,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T13:50:00Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-QH', price: 84.0 },
        metadata: { schemaVersion: 1 },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 3,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T14:00:00Z',
        payload: { meter_id: 'de-sub-4471', reading: 1204.8 },
        metadata: { schemaVersion: 1, reading_type: 'isp_start', source: 'MDL-50Hertz' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 4,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T14:05:00Z',
        payload: {
          trade_id: 'TRD-2024-78432',
          portfolio_id: 'brp-de-001',
          instrument_id: 'EPEX-DE-INTRA-QH',
          price: 86.2,
          quantity: -20,
        },
        metadata: { schemaVersion: 1, correlationId: 'isp-20241215-1400' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 5,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T14:15:00Z',
        payload: { meter_id: 'de-sub-4471', reading: 1243.0 },
        metadata: { schemaVersion: 1, reading_type: 'isp_end', source: 'MDL-50Hertz' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 6,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T14:16:00Z',
        payload: { instrument_id: 'EPEX-DE-IMBAL-QH', price: 850.0 },
        metadata: { schemaVersion: 1, price_type: 'imbalance_price', source: '50Hertz-settlement' },
      },
      {
        streamId: 'portfolio:brp-de-001',
        streamType: 'Portfolio',
        version: 7,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-16T09:30:00Z',
        payload: { meter_id: 'de-sub-4471', reading: 1241.9 },
        metadata: {
          schemaVersion: 1,
          reading_type: 'isp_end',
          corrects_version: 5,
          correction_reason: 'meter_calibration_adjustment',
          source: 'MDL-50Hertz-correction',
        },
      },
    ],
  },
  {
    id: 'remit-surveillance',
    title: 'REMIT Trade Surveillance',
    regulation: 'REMIT (EU) 1227/2011',
    description:
      'ACER spoofing investigation — immutable trail of rapid orders, cancellations, and price impact on EPEX-DE-INTRA-1700.',
    events: [
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 1,
        eventType: 'InstrumentListed',
        timestamp: '2024-12-15T06:00:00Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', name: 'EPEX DE Intraday 17:00 Delivery' },
        metadata: { schemaVersion: 1, market: 'EPEX_SPOT', delivery_zone: 'DE-LU' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 2,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:48:12Z',
        payload: {
          trade_id: 'ORD-2024-AW-5501',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 72.0,
          quantity: 10,
        },
        metadata: { schemaVersion: 1, trader_id: 'AW-TR-042', order_type: 'limit_buy' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 3,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T16:48:13Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', price: 78.5 },
        metadata: { schemaVersion: 1, trigger: 'order_book_update' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 4,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:49:04Z',
        payload: {
          trade_id: 'ORD-2024-AW-5514',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 95.0,
          quantity: 10,
        },
        metadata: { schemaVersion: 1, trader_id: 'AW-TR-042', order_type: 'limit_buy' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 5,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T16:49:05Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', price: 118.0 },
        metadata: { schemaVersion: 1, trigger: 'order_book_update' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 6,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:49:45Z',
        payload: {
          trade_id: 'ORD-2024-AW-5520',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 116.5,
          quantity: -120,
        },
        metadata: { schemaVersion: 1, trader_id: 'AW-TR-042', order_type: 'market_sell' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 7,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-15T16:50:02Z',
        payload: { instrument_id: 'EPEX-DE-INTRA-1700', price: 78.0 },
        metadata: { schemaVersion: 1, trigger: 'order_book_update' },
      },
      {
        streamId: 'instrument:EPEX-DE-INTRA-1700',
        streamType: 'Instrument',
        version: 8,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-15T16:52:00Z',
        payload: {
          trade_id: 'COMPL-2024-FREEZE-0042',
          portfolio_id: 'alphawatt-trading',
          instrument_id: 'EPEX-DE-INTRA-1700',
          price: 0.0,
          quantity: 0,
        },
        metadata: {
          schemaVersion: 1,
          trader_id: 'COMPLIANCE-SYSTEM',
          order_type: 'compliance_freeze',
          investigation_ref: 'ACER-2024-DE-SPOOF-0891',
        },
      },
    ],
  },
  {
    id: 'flexibility-market',
    title: 'Flexibility Market Clearing',
    regulation: 'Electricity Directive 2019/944',
    description:
      'DSO/aggregator delivery dispute — compare Method A (3.2 MW under-delivery) vs Method B (4.8 MW within tolerance) using the same meter data.',
    events: [
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 1,
        eventType: 'FlexibilityBidSubmitted',
        timestamp: '2024-12-15T08:00:00Z',
        payload: {
          bid_id: 'FLEX-2024-NL-0847',
          aggregator_id: 'flexco-nl',
          market_id: 'GOPACS-NL-SOUTH',
          capacity_mw: 5.0,
          price_eur_per_mwh: 145.0,
        },
        metadata: { schemaVersion: 1 },
      },
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 2,
        eventType: 'FlexibilityActivated',
        timestamp: '2024-12-15T16:45:00Z',
        payload: {
          bid_id: 'FLEX-2024-NL-0847',
          activated_by: 'enexis-dso',
          congestion_area: 'NL-SOUTH-SUB-12',
        },
        metadata: { schemaVersion: 1, source: 'GOPACS-activation-engine' },
      },
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 3,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T17:00:00Z',
        payload: { meter_id: 'nl-flex-001', reading: 4521.3 },
        metadata: { schemaVersion: 1, reading_type: 'activation_start' },
      },
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 4,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T17:00:00Z',
        payload: { meter_id: 'nl-flex-002', reading: 2187.6 },
        metadata: { schemaVersion: 1, reading_type: 'activation_start' },
      },
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 5,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T18:00:00Z',
        payload: { meter_id: 'nl-flex-001', reading: 4522.1 },
        metadata: { schemaVersion: 1, reading_type: 'activation_end' },
      },
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 6,
        eventType: 'MeterReadingRecorded',
        timestamp: '2024-12-15T18:00:00Z',
        payload: { meter_id: 'nl-flex-002', reading: 2188.2 },
        metadata: { schemaVersion: 1, reading_type: 'activation_end' },
      },
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 7,
        eventType: 'FlexibilityDeliveryVerified',
        timestamp: '2024-12-15T19:30:00Z',
        payload: {
          bid_id: 'FLEX-2024-NL-0847',
          verified_by: 'enexis-dso',
          methodology: 'method_a_10day_average',
          delivered_mw: 3.2,
          result: 'under_delivery',
          penalty_eur: 580.0,
        },
        metadata: { schemaVersion: 1 },
      },
      {
        streamId: 'flex-bid:FLEX-2024-NL-0847',
        streamType: 'FlexibilityBid',
        version: 8,
        eventType: 'FlexibilityDeliveryVerified',
        timestamp: '2024-12-16T10:15:00Z',
        payload: {
          bid_id: 'FLEX-2024-NL-0847',
          verified_by: 'flexco-nl',
          methodology: 'method_b_regression_adjusted',
          delivered_mw: 4.8,
          result: 'within_tolerance',
        },
        metadata: { schemaVersion: 1, disputes_version: 7 },
      },
    ],
  },
  {
    id: 'cross-border-capacity',
    title: 'Cross-Border Capacity Allocation',
    regulation: 'CACM (EU) 2015/1222',
    description:
      'Curtailment audit — replay flow-based parameters from two TSOs, Euphemia clearing, congestion revenue distribution, and the 500→350 MW curtailment.',
    events: [
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 1,
        eventType: 'CrossBorderFlowRecorded',
        timestamp: '2024-12-14T10:00:00Z',
        payload: {
          flow_id: 'FB-RTE-20241215-H18',
          tso: 'RTE',
          bidding_zone: 'FR',
          cnec: 'Vigy-Uchtelfangen',
          ram_mw: 2100,
        },
        metadata: { schemaVersion: 1, source: 'RTE-CGMES-export' },
      },
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 2,
        eventType: 'CrossBorderFlowRecorded',
        timestamp: '2024-12-14T10:05:00Z',
        payload: {
          flow_id: 'FB-AMP-20241215-H18',
          tso: 'Amprion',
          bidding_zone: 'DE-LU',
          cnec: 'Vigy-Uchtelfangen',
          ram_mw: 1850,
        },
        metadata: { schemaVersion: 1, source: 'Amprion-CGMES-export' },
      },
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 3,
        eventType: 'CapacityAllocationRequested',
        timestamp: '2024-12-14T12:00:00Z',
        payload: {
          request_id: 'CAP-REQ-2024-IF-1847',
          participant: 'IndustriFR',
          direction: 'DE-to-FR',
          requested_mw: 500,
        },
        metadata: { schemaVersion: 1, source: 'SDAC-order-book' },
      },
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 4,
        eventType: 'CrossBorderFlowRecorded',
        timestamp: '2024-12-14T12:42:00Z',
        payload: {
          flow_id: 'EUPH-FLOW-20241215-H18-DE-FR',
          tso: 'NEMO-committee',
          algorithm: 'Euphemia',
          commercial_flow_mw: 1420,
          curtailment_applied: true,
        },
        metadata: { schemaVersion: 1, source: 'Euphemia-SDAC-results' },
      },
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 5,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-14T12:42:00Z',
        payload: { instrument_id: 'SDAC-DA-DE-LU-H18', price: 85.0 },
        metadata: { schemaVersion: 1, price_type: 'day_ahead_clearing', bidding_zone: 'DE-LU' },
      },
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 6,
        eventType: 'PriceTickRecorded',
        timestamp: '2024-12-14T12:42:00Z',
        payload: { instrument_id: 'SDAC-DA-FR-H18', price: 130.0 },
        metadata: { schemaVersion: 1, price_type: 'day_ahead_clearing', bidding_zone: 'FR' },
      },
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 7,
        eventType: 'CongestionRevenueDistributed',
        timestamp: '2024-12-14T13:00:00Z',
        payload: {
          revenue_id: 'CR-20241215-H18-DE-FR',
          border: 'DE-FR',
          total_revenue_eur: 63900.0,
          price_spread_eur: 45.0,
        },
        metadata: { schemaVersion: 1, methodology: 'CACM-Art-63' },
      },
      {
        streamId: 'da-allocation:2024-12-15-H18',
        streamType: 'DayAheadAllocation',
        version: 8,
        eventType: 'TradeExecuted',
        timestamp: '2024-12-14T13:00:00Z',
        payload: {
          trade_id: 'ALLOC-2024-IF-1847-CURTAILED',
          portfolio_id: 'industrifr-portfolio',
          instrument_id: 'SDAC-DA-FR-H18',
          price: 130.0,
          quantity: 350,
        },
        metadata: {
          schemaVersion: 1,
          original_request_mw: 500,
          allocated_mw: 350,
          curtailed_mw: 150,
          curtailment_reason: 'flow_based_constraint',
        },
      },
    ],
  },
];
